const fontsize = 12
const commonColor = '#0ab8b4'
const formFontsize = 17
const borderRadius = 30
const linkColor= "#f7a16a"
const headingColor='#3f3d56'
const textColor='#3f3d56'
const fontColor ='#888797'
const headingSize = 26
const subHeadingSize = 20
const titleSize = 22
const menuColor ='#3f3d56'
const cartBtnColor='#ffa86f'
import Fonts from '../Common/Fonts'
module.exports = {
    activecolor:{
        color:commonColor,
    },
    tintcolor:{
        color:headingColor,
    },
    placeholdercolor:{
        color:textColor,
    },
    wrapContainer: {
        flex:1,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#fff'
    },
    container: {
        flex:1,
        backgroundColor:'#fff'
    },
    greyBg:{
        backgroundColor:'#edf0f4'
    },
    innerContainer: {
        flex:1,
    },
    logo:{
        width:110,
        height:110,
        resizeMode:'contain'
    },
    loginContainer: {
        backgroundColor: '#000000',
        flex:1,
    },
    loginBackground:{
        flex:1,
        justifyContent:'flex-end',
        paddingVertical:20,
    },
    inputField:{
        height:45,
        backgroundColor:'#fff',
        borderRadius:borderRadius,
        textAlign:'center',
        marginBottom:15,
        fontSize:formFontsize,
        paddingHorizontal:20,
        color:fontColor
    },
    inputFieldBorder:{
        backgroundColor:'transparent',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#d6d6d6',
        textAlign:'left',
    },
    loginWrap:{
        width:'100%',
        paddingHorizontal:30,
    },
    passwordImageWrap:{
        alignItems:'center',
        marginBottom:20
    },
    passwordImage:{
        width:118,
        height:118,
        resizeMode:'contain',
    },
    commonButton:{
        height:50,
        backgroundColor:commonColor,
        borderRadius:borderRadius,
        textAlign:'center',
        justifyContent:"center",
        textTransform:'uppercase',
        fontSize:formFontsize,
        lineHeight:57,
        color:'#fff',
        marginBottom:15,
        fontSize:18
    },
    commonButtonTxt:{
      
        textAlign:'center',
        textTransform:'uppercase',
        fontSize:formFontsize,
        color:'#fff',
        fontSize:18
    },
    circle:{
        height:25,
        width:25,
        backgroundColor:'#ffffff',
        borderRadius:50,
        alignItems:'center',
        justifyContent:'center',
        marginRight:15
    },
    checkCircle:{
        height:17,
        width:17,
        backgroundColor:commonColor,
        borderRadius:50
    },
    loginRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    loginColumn:{
        flexDirection:'row',
        justifyContent:'center'
    },
    loggedText:{
        color:'#fff',
        fontSize:17,
        marginLeft:0,
        fontWeight:'bold',
        paddingTop:2
    },
    forgotLink:{
        fontSize:18,
        color:linkColor,
        fontWeight:'bold'
    },
    resendLink:{
        fontSize:21,
        color:'#ffaf7a',
    },
    inputFieldLine:{
        borderBottomWidth:5,
        borderStyle:'solid',
        borderBottomColor:'#d6d6d6',
        width:65,
        textAlign:'center',
        fontSize:40
    },
    inputActiveLine:{borderBottomColor:cartBtnColor},
    verificationInput:{
        flexDirection:'row',
        marginBottom:40,
        justifyContent:'space-between'
    },
    resendCode:{
        alignItems:'center',
        marginTop:30
    },
    loginOrRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop:10,
        marginBottom:15
    },
    orLine:{
        backgroundColor:'#ffffff',
        width:'42%',
        height:1,
        opacity:0.3,
        marginTop:5
    },
    orText:{
        color:'#ffffff',
        fontSize:22,
        textAlign:'center',
    },
    borderButton:{
        backgroundColor:'transparent',
        borderWidth:1,
        borderColor:'#ffffff'
    },
    borderColorButton:{
        backgroundColor:'transparent',
        borderWidth:1,
        borderColor:textColor,
        color:textColor
    },
    loginBottom:{
        marginTop:15
    },
    loginText:{
        fontSize:fontsize,
        color:'#ffffff',
        textAlign:'center',
        fontWeight:'bold'
    },
    linkLine:{
        textDecorationLine:'underline',
        marginHorizontal:3
    },
    textCenter:{textAlign:'center'},
    textLeft:{textAlign:'left'},
    textRight:{textAlign:'right'},
    heading:{
        fontSize:headingSize,
        fontWeight:'bold',
        color:headingColor,
        marginBottom:15
    },
    subHeading:{
        fontSize:subHeadingSize,
        color:fontColor,
        marginBottom:20
    },
    headingWrap:{paddingHorizontal:25},
    headingWrapMargin:{
        marginBottom:25
    },
    headingMargin:{
        marginBottom:15
    },
    profileImageWrap:{
        alignItems:'center',
        marginBottom:25
    },
    profileImage:{
        width:150,
        height:150,
        borderRadius:100,
        resizeMode:'stretch',
    },
    profileImageSec:{
      //  padding:10,
      borderColor:"white",
        backgroundColor:'#ffffff',
        borderRadius:100,

        shadowColor: '#ddd',
        shadowOffset: {width: 0,height: 1,},
        shadowOpacity: 0.9,
        shadowRadius: 1,
        elevation: 3,
    },
    plusIconSec:{
        position:'absolute',
        right:0,
        bottom:0,
        zIndex:1
    },
    plusIcon:{
        width:38,
        height:38,
        resizeMode:'contain',
    },
    sliderImage:{
        width:400,
        height:150,
        borderRadius:7
    },
    homeTop:{
        backgroundColor:"#ffffff",
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingHorizontal:30,
        paddingVertical:15
    },
    locationTopWrap:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    locationIcon:{
        width:32,
        height:32,
        resizeMode:'contain',
        marginRight:10
    },
    locationText:{
        fontSize:20,
        color:'#9e9e9e'
    },
    toggle:{
        width:32,
        height:32,
        resizeMode:'contain',
    },
    bannerWrap:{
        paddingVertical:30,
        paddingLeft:10
    },
    categorySection:{
        paddingHorizontal:8,
        paddingBottom:25
    },
    headingTitle:{
        fontSize:titleSize,
        color:headingColor,
        marginBottom:15,
        textAlign:'center',
    },
    categoryWrap:{
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'center',
        
    },
    categoryList:{
        width:'25%',
        padding:2,
        height:90,
       
    },
    categoryItem:{
        backgroundColor:'#fff',
        height:'100%',     
        alignItems:'center',
        justifyContent:'center',
        padding:5,
        borderRadius:3
    },
    categoryName:{
        textAlign:'center',
        fontSize:13
    },
    categoryImage:{
        width:40,
        resizeMode:'contain',
        marginBottom:5
    },
    sliderSection:{
        backgroundColor:cartBtnColor,
        borderTopLeftRadius:borderRadius,
        borderTopRightRadius:borderRadius,
        paddingTop:30,
       // paddingLeft:25,
       paddingHorizontal:10,
        paddingBottom:90
    },
    sliderHeading:{
        flexDirection:'row',
       // paddingRight:25,
        justifyContent:'space-between',
        alignItems:'center'
    },
    textColor:{
        color:'#fff',
        fontSize:22,
        marginBottom:15,
        marginTop:10,
        textAlign:'center',
    },
    whiteButton:{
        backgroundColor:'#fff',
        fontSize:21,
        paddingHorizontal:15,
        paddingVertical:5,
        borderRadius:borderRadius,
        color:'#525252'
    },
    productList:{
        marginRight:10
    },
    productWrap:{
        flexDirection:'row',
        marginTop:10,
    },
    productItem:{
        backgroundColor:'#fff',
        borderRadius:7,
        alignItems:'center',
        padding:10,
        width:130
    },
    productImage:{
        height:90,
        marginBottom:7,
        resizeMode:'contain'
    },
    productFullImage:{
        marginBottom:0,
        resizeMode:'cover',
        height:93,
        width:93,
    },
    productName:{
        fontSize:15,
        color:fontColor
    },
    productPrice:{
        fontSize:15,
        color:fontColor
    },
    storeSection:{
        backgroundColor:'#edf0f4',
        borderTopLeftRadius:borderRadius,
        borderTopRightRadius:borderRadius,
        paddingTop:30,
        paddingLeft:25,
        paddingBottom:60,
        top:-30
    },
    storeMargin:{
        marginTop:10
    },
    accountWrap:{
        paddingVertical:30
    },
    accountEditWrap:{paddingTop:15,paddingBottom:30},
    accountImageWrap:{
        marginBottom:20
    },
    settingsSec:{
        position:'absolute',
        top:-10,
        right:20,
        alignItems:'center'
    },
    settingsIcon:{
        width:28,
        marginBottom:1
    },
    settingsText:{
        fontSize:16,
        color:textColor
    },
    accountLabel:{
        fontSize:titleSize,
        fontWeight:'bold',
        color:headingColor
    },
    accountText:{
        fontSize:titleSize,
        color:'#b2b1bb'
    },
    accountContent:{
        paddingHorizontal:50,
    },
    accountEditContent:{
        paddingHorizontal:30,
        marginTop:10
    },
    accountDetails:{
        paddingTop:30
    },
    accountImage:{
        width:80,
        height:80,
        borderRadius:100,
        resizeMode:'stretch',
    },
    menuTop:{
        alignItems:'center',
        paddingTop:30,
        paddingBottom:15,
        backgroundColor:menuColor
    },
    menuHeading:{
        fontSize:titleSize,
        fontWeight:'bold',
        color:'#ffffff',
        marginBottom:15,
        marginTop:10
    },
    smallImageSec:{
        padding:5
    },
    menuSection:{
    
        paddingTop:20,
        paddingBottom:30,
        paddingLeft:30,
        paddingRight:20
    },
    addButton:{
        flexDirection:'row',
        marginTop:3,
        width:86,
    },
    addIcon:{
        width:23,
        height:23,
        textAlign:'center',
        backgroundColor:'#d9d9d9',
        fontSize:25,
        color:'#fff',
        borderRadius:100,
        lineHeight:28
    },
    addCount:{
        width:40,
        height:25,
        textAlign:'center',
        fontSize:26,
        color:textColor,
        backgroundColor:'#fff',
        lineHeight:30,
        
    },
    productListingSec:{
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:'#fff',
        marginBottom:20,
        borderRadius:10,
        justifyContent:'space-between'
    },
    cartIconButton:{
        backgroundColor:cartBtnColor,
        paddingHorizontal:5,
        paddingVertical:8,
        borderRadius:borderRadius,
        width:60,
        alignItems:'center'
    },
    cartIcon:{
        fontSize:24,
        color:'#fff',
    },
    productItemListing:{
        paddingTop:20,
        paddingRight:15,
        paddingLeft:15,
        paddingBottom:10
    },
    productListImage:{
        borderRightColor:'#f2f2f2',
        borderRightWidth:1,
        borderStyle:'solid',
        width:'28%',
        paddingHorizontal:15,
        paddingVertical:7,
        borderRadius:10
    },
    productListContent:{
        width:'72%',
        paddingRight:3,
        paddingLeft:12,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        flexWrap:'wrap'
    },
    fullListImage:{
        paddingHorizontal:0,
        paddingVertical:0,
    },
    productItemImage:{
        width:'100%'
    },
    productListDetails:{
        width:'70%',
        paddingRight:7,
    },
    productConfirmDetails:{
        width:'100%',
    },
    productSelectSec:{
        width:'98%',
        borderStyle:'solid',
        borderWidth:1,
        borderColor:'#d9d9d9',
        borderRadius:borderRadius,
        paddingHorizontal:7,
        marginTop:10
    },
    productSelectSecSmall:{
        width:'70%'
    },
    productSelect:{
        width:'100%',
        color:textColor,
        height:28,
        fontsize:14
    },
    cartBtnSection:{
        width:'30%',
        paddingRight:5,
        alignItems:'flex-end',
    },
    productListName:{
        fontSize:18,
        color:textColor,
        marginBottom:3
    },
    productConfirmPrice:{
        fontSize:18,
        color:commonColor
    },
    productListPrice:{
        fontSize:18,
        color:cartBtnColor,
        marginBottom:3,
    },
    bottomTotalPrice:{
        backgroundColor:'#fff',
        flexDirection:'row',
        justifyContent:'space-between',
        paddingHorizontal:30,
        paddingVertical:10,
        alignItems:'center',        
    },
    bottomTotalSec:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    cartButtontIcon:{
        fontSize:40,
        color:'#8b8a99'
    },
    largeButton:{
        marginBottom:0,
        paddingHorizontal:20,
        fontSize:18,
        lineHeight:57,
        height:50,
    },
    bottomTotalIcon:{
        marginRight:15
    },
    bottomItemCount:{
        color:'#8c8b9a',
        fontSize:16,
        marginBottom:1
    },
    bottomPrice:{
        fontSize:19,
        color:commonColor
    },
    storeListSec:{
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:'#fff',
        marginBottom:20,
        borderRadius:10,
        paddingHorizontal:25,
        paddingVertical:10
    },
    storeListImage:{
        width:70,
        height:70,
        resizeMode:'contain',
        borderRadius:100,
    },
    storeImage:{
        width:90,
        height:90,
        resizeMode:'cover',
        marginBottom:7,
        borderColor:'#ddd',
        borderWidth:1,
        borderStyle:'solid',
        borderRadius:100,
    },
    storeListImage:{
        //width:'30%',
        marginRight:15
    },
    storeListDetails:{
        paddingRight:15,
        width:'70%',
    },
    storeImageSec:{
        shadowColor: '#ddd',
        shadowOffset: {width: 0,height: 1,},
        shadowOpacity: 0.9,
        shadowRadius: 1,
        elevation: 3,
        padding:7,
        borderRadius:100,
    },
    storeImageItem:{
        width:80,
        height:80,
        resizeMode:'cover',
        borderRadius:100,
        backgroundColor:'#fff'
    },
    storeListName:{
        fontSize:21,
        color:'#4c4c4c',
        fontWeight:'bold',
    },
    storeListLocation:{
        fontSize:21,
        color:'#4c4c4c',
    },
    tagSection:{
        flexDirection:'row',
        paddingTop:20,
        paddingLeft:15,
        paddingBottom:10
    },
    tags:{
        paddingHorizontal:20,
        backgroundColor:'#dbdee4',
        color:textColor,
        marginRight:10,
        fontSize:18,
        paddingVertical:10,
        borderRadius:borderRadius
    },
    tagActive:{
        backgroundColor:commonColor,
        color:'#ffffff'
    },
    storeHeadingSec:{
        paddingHorizontal:20,
        paddingTop:30,
        paddingBottom:10
    },
    storeHeadingText:{
        fontSize:25,
        color:'#000000'
    },
    storeHeadingName:{
        fontSize:25,
        fontWeight:'bold',
        color:'#000000',
        marginBottom:5
    },
    storeHeadingCount:{
        fontSize:25,
        color:commonColor
    },
    storeTopSection:{
        backgroundColor:menuColor,
        marginBottom:10,
        paddingVertical:17,
        paddingHorizontal:30
    },
    innerStoreView:{
        paddingHorizontal:15,
        paddingTop:20
    },
    storeInnerName:{
        fontSize:26,
        color:'#fff',
        fontWeight:'bold',
    },
    storeInnerLocation:{
        fontSize:22,
        color:'#fff',
    },
    verifySec:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginBottom:30
    },
    selectVerifySec:{
        width:'28%',
        borderStyle:'solid',
        borderWidth:1,
        borderColor:'#d9d9d9',
        borderRadius:borderRadius,
        paddingHorizontal:10,
        marginTop:0,
        height:45,
    },
    verifySelectField:{
        width:'100%',
        height:45,
        color:fontColor,
    },
    verifyInputSec:{
        width:'72%',
        paddingLeft:10
    },
    verifyInputField:{
        marginBottom:0,
        textAlign:'center'
    },
    productRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    cancelImage:{
        width:23,
        height:23,
        resizeMode:'cover'
    },
    removeItem:{
        position:'absolute',
        right:7,
        top:0
    },
    storeTopRow:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:6
    },
    storeBtn:{
        textTransform:'uppercase',
        fontSize:14,
        color:textColor,
        backgroundColor:'#fff',
        paddingHorizontal:6,
        paddingVertical:7,
        borderRadius:borderRadius,
        textAlign:'center'
    },
    removeBtn:{
        backgroundColor:'#ee1b27',
        color:'#fff'
    },
    priceSection:{
        borderRadius:10,
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#cbcbcb',
        backgroundColor:'#fff',
        paddingVertical:25,
        paddingHorizontal:40
    },
    priceStoreName:{
        fontSize:26,
        color:textColor,
        fontWeight:'bold',
    },
    priceListText:{
        fontSize:21,
        color:textColor,
    },
    confirmRow:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:10
    },
    orderSummaryStore:{
        marginBottom:20
    },
    totalPriceSection:{
        paddingHorizontal:15,
        paddingVertical:20
    },
    priceSectionColor:{
        backgroundColor:commonColor
    },
    priceTextColor:{
        color:'#fff'
    },
    confirmFormSec:{
        paddingBottom:30,
        paddingHorizontal:15,
        paddingTop:10
    },
    formSection:{
        paddingVertical:30,
        paddingHorizontal:15, 
    },
    selectForm:{
        width:'100%',
        borderStyle:'solid',
        borderWidth:1,
        borderColor:'#d9d9d9',
        borderRadius:borderRadius,
        paddingHorizontal:13,
        marginBottom:10,
        backgroundColor:'#fff'
    },
    selectFormPicker:{
        width:'100%',
        color:textColor,
        height:45,
        fontsize:formFontsize,
    },
    formInputField:{
        height:45,
        backgroundColor:'#fff',
        borderRadius:borderRadius,
        marginBottom:10,
        fontSize:formFontsize,
        paddingHorizontal:20,
        color:textColor,
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#d6d6d6',
        textAlign:'left',
        placeholderTextColor: 'red'
    },
    commonColorButton:{
        backgroundColor:textColor
    },
    promoSection:{
        paddingVertical:20
    },
    formButtonSection:{
        marginVertical:20
    },
    formList:{
        marginBottom:0,
        justifyContent:'center'
    },
    shippingBar:{
        height:8,
        backgroundColor:'#c7c7c7',
        width:'50%',        
        flexDirection:'row',
        justifyContent:'space-between'
    },
    shippingBarSec:{
        marginTop:30,
        marginBottom:15,
        paddingHorizontal:40,
        flexDirection:'row',
    },
    shippingBarRound:{
        width:25,
        height:25,
        backgroundColor:'#fff',
        borderRadius:100,
        elevation:5,
        shadowColor: '#ddd',
        shadowRadius: 3,
        shadowOffset: {width: 0,height: 1,},
        alignSelf:'center',
        justifyContent:'center'
    },
    shippingRound:{
        width:18,
        height:18,
        backgroundColor:'#fff',
        borderRadius:100,
        alignSelf:'center',
    },
    shippingBarRoundSecond:{
        left:-8
    },
    shippingBarColor:{
        backgroundColor:commonColor
    },
    cardImageSection:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginBottom:15,
    },
    cardImageList:{
        width:'50%',
        paddingHorizontal:3
    },
    cardImage:{
        width:'100%',
        height:70,
        resizeMode:'stretch'
    },
    lockImage:{
        position:'absolute',
        right:20,
        width:18,
        height:21,
        resizeMode:'cover',
        top:11,
        opacity:0.5
    },
    paymentSection:{
        padding:30
    },
    paymentList:{
        flexDirection:'row',
        alignItems:'center',
        marginBottom:35
    },
    paymentImage:{
        width:65,
        height:45,
        resizeMode:'stretch'
    },
    addCardImage:{
        width:33,
        height:22,
        resizeMode:'stretch'
    },
    paymentImageSec:{
        paddingRight:15,
    },
    cardTextName:{
        color:'#3F3D56',
     fontFamily:Fonts.MontserratLight,
        fontSize:19,
    },
    cardTextDeatils:{
        color:'#000',
        fontSize:19,
        fontFamily:Fonts.MontserratLight,
    },
    addCardText:{
        color:'#787788',
        fontSize:19,
        fontFamily:Fonts.MontserratLight,
    },
    paymentListContent:{
        width:'70%'
    },
    addCardContent:{
        width:'80%',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    thankyouSection:{
        alignItems:'center',
        justifyContent:'center',
        marginTop:50,
        marginBottom:15
    },
    thankyouImage:{
        width:100,
        height:92,
        resizeMode:'stretch',
        marginBottom:15
    },
    thankyouTitle:{
        fontSize:32,
        color:'#000',
        marginBottom:5
    },
    thankyouText:{
        fontSize:21,
        color:'#000',
        marginBottom:5
    },
    couponSection:{
        padding:30,
    },
    couponImage:{
        width:170,
        height:99,
        resizeMode:'stretch',
        marginBottom:15
    },
    couponSectionList:{
        alignItems:'center',
        marginBottom:15
    },
    couponTitle:{
        fontSize:32,
        color:headingColor,
        marginBottom:5,
        fontWeight:'bold'
    },
    inputFieldLineSmall:{
        width:40,
        fontSize:24,
        color:textColor
    },
    inputColorActiveLine:{borderBottomColor:commonColor},
    verificationInputMargin:{
        marginBottom:30
    },
    shareListList:{
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:15,
        paddingVertical:10,
        borderColor:'#c4c3cb',
        borderRadius:7,
        borderStyle:'solid',
        borderWidth:1,
        marginBottom:15
    },
    shareImage:{
        //width:23,
        height:25,
        resizeMode:'contain'
    },
    shareImageSec:{
        width:40,
    },
    shareText:{
        color:'#3F3D56',
        fontSize:16,
        fontFamily:Fonts.OpenSansRegular,
    },
    mailImageWrap:{
        marginBottom:45
    },
    mailContent:{
        justifyContent:'center',
        alignItems:'center',
        marginTop:15
    },
    mailText:{
        backgroundColor:'#00000029',
        fontSize:18,
        paddingHorizontal:25,
        paddingVertical:10,
        color:textColor,
        fontFamily:Fonts.OpenSansRegular,
        borderRadius:7,
        textAlign:'center'
    },
    menuSection:{
        paddingTop:20,
        paddingLeft:30,
        paddingRight:20,
        paddingBottom:30
    },
    menuList:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        justifyContent:'space-between',
       // backgroundColor:"red",
        height:60,
        marginBottom:10,
        borderBottomWidth:1,
        borderColorButton:'black'
        //width:'80%'
    },
    arrowIcon:{
        width:20,
        resizeMode:'center',
    },
    menuText:{
        fontSize:20,
        color:textColor
    },
    icons: {
        width: 25,
    },
    ButtonSection:{
        marginTop:30
    },
    searchBar:
    {
      flexDirection:'row',
      marginRight:20,
      alignItems:'center'
    },
    searchBarInput:{
        backgroundColor:'#ebebee',
        borderRadius:borderRadius,
        height:40,
        width:230,
        fontSize:18,
        paddingHorizontal:15,
        marginRight:7
    },
    searchIconBtn:{
        backgroundColor:commonColor,
        borderRadius:borderRadius,
        alignItems:'center',
        width:35,
        height:35,
        justifyContent:'center'
    },
    searchIcon:{
        width:22,
        height:22
    }
}